application-description: project.description
application-version: project.version

server:
  port: 8080

spring:
  application:
    name: ms-person
  datasoruce:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: common
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: '/swagger-ui.html'
    operationsSorter: method
app:
  write:
    enabled: false