application-description: project.description
application-version: project.version

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: ms-person
  datasoruce:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: common
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: '/swagger-ui.html'
    operationsSorter: method
#app:
#  write:
#    enabled: false