apiVersion: v1
kind: ResourceQuota
metadata:
  name: ms-person
spec:
  hard:
    requests.cpu: "500m" # one pod requesting CPU of 500m(Half of 1vCPU) and 256MiB of memory
    requests.memory: 1Gi
    limits.cpu: "700m" # one pod CPU  limit 1000m(1vCPU) and 521Mib of memory
    limits.memory: 2Gi