apiVersion: v1
kind: Secret
metadata:
  name: ms-project-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  ms_db_username: YmFyCg==
  ms_db_passwordname: YmFyCg==