application-description: project.description
application-version: project.version

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
  application:
    name: ms-person
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: common
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
  messages:
    basename: i18n/messages
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: '/swagger-ui.html'
    operationsSorter: method